##############################################
# 🔥 IMPORTANT 🔥
# These variables MUST stay in sync with:
#   ➜ IgniteLifeApi/appsettings.Testing.json
#
# The database name, user, password, host, 
# and port must exactly match the connection 
# string used in your testing configuration.
##############################################

services:
  test_db:
    image: postgres:17-alpine
    container_name: test_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "testdb" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "5433:5432"
    networks:
      - api_test_network

  tests:
    build:
      context: .
      dockerfile: IgniteLifeApi.Tests/Dockerfile.tests
    container_name: api_tests
    environment:
      ConnectionStrings__DefaultConnection: "Host=test_db;Port=5432;Database=testdb;Username=postgres;Password=postgres"
    depends_on:
      test_db:
        condition: service_healthy
    networks:
      - api_test_network

networks:
  api_test_network:
