name: CI - Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify .env.test exists
        run: cat .env.test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run tests via docker-compose
        run: docker compose --env-file .env.test up --build --abort-on-container-exit --exit-code-from tests tests

      - name: Show DB logs if fail
        if: failure()
        run: docker compose logs test_db

      - name: Tear down Docker Compose
        if: always()
        run: docker compose down -v
