name: CI - Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ✅ Ensure .env.test is available
      - name: Verify .env.test file
        run: |
          if [ ! -f ".env.test" ]; then
            echo ".env.test not found. Creating from GitHub secrets..."
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env.test
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env.test
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env.test
            echo "DB_HOST=localhost" >> .env.test
            echo "DB_PORT=5432" >> .env.test
          fi
          cat .env.test

      - name: Run tests via docker-compose
        run: docker compose --env-file .env.test up --build --abort-on-container-exit --exit-code-from tests tests

      # ✅ Collect database logs if it fails
      - name: Show database logs (on failure)
        if: failure()
        run: docker compose logs test_db

      - name: Tear down Docker Compose
        if: always()
        run: docker compose down -v
